/*
 * TIMER0_TYPES.h
 *
 *      Author: Ahmed Khalifa
 */

#ifndef TIMER0_TYPES_H_
#define TIMER0_TYPES_H_

/* Section : Includes */

/* Section: Data Type Declarations */
typedef enum
{
	TIMER0_OPERATION_MODE_NORMAL,
	TIMER0_OPERATION_MODE_PHASE_CORRECT_PWM,
	TIMER0_OPERATION_MODE_CTC,
	TIMER0_OPERATION_MODE_FAST_PWM
} TIMER0_OperationMode_t;

typedef enum
{
	TIMER0_OUTPUT_COMPARE_MODE_DISABLE,
	TIMER0_OUTPUT_COMPARE_MODE_TOGGLE_ON_COMPARE_MATCH,
	TIMER0_OUTPUT_COMPARE_MODE_CLEAR_ON_COMPARE_MATCH,
	TIMER0_OUTPUT_COMPARE_MODE_SET_ON_COMPARE_MATCH
} TIMER0_NonPWMOutputCompareMode_t;

typedef enum
{
	TIMER0_FAST_PWM_OUTPUT_COMPARE_MODE_DISABLE,
	TIMER0_FAST_PWM_OUTPUT_COMPARE_MODE_NON_INVERTING = 2,
	TIMER0_FAST_PWM_OUTPUT_COMPARE_MODE_INVERTING = 3
} TIMER0_FastPWMOutputCompareMode_t;

typedef enum
{
	TIMER0_PHASE_CORRECT_PWM_OUTPUT_COMPARE_MODE_DISABLE,
	TIMER0_PHASE_CORRECT_PWM_OUTPUT_COMPARE_MODE_CLEAR_ON_UP= 2,
	TIMER0_PHASE_CORRECT_PWM_OUTPUT_COMPARE_MODE_SET_ON_UP= 3
} TIMER0_PhaseCorrectPWMOutputCompareMode_t;

typedef enum
{
	TIMER0_CLOCK_DISABLED,
	TIMER0_CLOCK_DIV_1,
	TIMER0_CLOCK_DIV_8,
	TIMER0_CLOCK_DIV_64,
	TIMER0_CLOCK_DIV_256,
	TIMER0_CLOCK_DIV_1024,
	TIMER0_CLOCK_EXTERNAL_ON_FALLING,
	TIMER0_CLOCK_EXTERNAL_ON_RISING
} TIMER0_ClockSource_t;

typedef struct {
	TIMER0_ClockSource_t 		TIMER0_Clock : 3 ;
	TIMER0_OperationMode_t		TIMER0_OperationMode : 2 ;
	uint8_t						TIMER0_OutputCompare_Mode : 2;
} TIMER0_Cfg_t;

/* Section: Macro Declarations */

/* Defining Masks for TIMER0 Registers' Bits*/
#define TIMER0_CLOCK_SELECT_MASK			0xF8
#define TIMER0_MODE_SELECT_MASK				0xB7
#define TIMER0_COMPARE_MODE_SELECT_MASK		0xCF

/* Section: Macro Functions Declarations */

/* Section: Function Declarations */

#endif /* TIMER0_TYPES_H_ */
